name: Build Tailwind CSS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          yarn install

      - name: Build Tailwind CSS
        run: |
          yarn build:css

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push built CSS
        run: |
          git add assets/css/tailwind.css
          git commit -m "Build Tailwind CSS"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
